name: 'Build and deploy'

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders

      - name: build and push container image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.ref_name == 'main' }}
          tags: ghcr.io/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
